HelloWorld/src/main/HelloWorldWeb/Controllers/HelloWorldController.cs
using System;
using System.Web;
using System.Web.Mvc;
using HelloWorld;
using HelloWorldWeb.Models;

namespace HelloWorldWeb.Controllers
{
    public class HelloWorldController : Controller
    {
        // GET: HelloWorld
        public ActionResult Index()
        {
            var model = CreateIndexViewModel();
            return View("Index", model);
        }

        public ActionResult Add(String message)
        {
            var helloMessageManager = new HelloMessageManager();
            helloMessageManager.AddMessage(message);
            var model = CreateIndexViewModel();
            return View("Index", model);
        }

        public ActionResult Delete(int id)
        {
            var helloMessageManager = new HelloMessageManager();
            helloMessageManager.DeleteMessage(id);
            var model = CreateIndexViewModel();
            return View("Index", model);
        }

        private static HelloWorldIndexModel CreateIndexViewModel()
        {
            var helloMessageManager = new HelloMessageManager();
            var model = new HelloWorldIndexModel();
            model.Messages = helloMessageManager.GetMessages();
            model.QueryTime = new DateTime(1999, 01, 02);
            return model;
        }
    }
}

HelloWorld/src/main/HelloWorldWeb/Views/HelloWorld/Index.cshtml
@model HelloWorldWeb.Models.HelloWorldIndexModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div>
            @foreach (var helloMessage in @Model.Messages)
            {
                <div>
                    <span>@helloMessage.Id</span>
                    <span>@helloMessage.Message</span>
                </div>
            }  
        </div>
        <div>
            @Model.QueryTime
        </div>
        @*
        @using (Html.BeginForm("Add", "HelloWorld"))
        {
            @Html.TextBox("message")
            <input type="submit" value="Add" />
        }
        *@
        @using (Html.BeginForm("Delete", "HelloWorld"))
        {
            <script language="javascript">
                var x = '@AppDomain.CurrentDomain.BaseDirectory';
            </script>
            @Html.TextBox("id")
            <input type="submit" value="Delete" />
        }

    </body>
</html>